stages:
  - test
  - build

variables:
  NODE_VERSION: "8"

#
# test stage tasks
#
test_project:
  stage: test
  before_script:
    - . envcfg
    - npm install
  script:
    - npm run lint
    - npm run test


#
# build stage tasks
#
build_project:
  stage: build
  artifacts:
    name: "$CI_PROJECT_NAMESPACE.$CI_PROJECT_NAME.$CI_PIPELINE_ID"
    paths:
      - ./
  before_script:
    - . envcfg
    - npm install
  script:
    - npm run
  after_script:
    - rm -rf node_modules .git
    - NODE_ENV="production" npm install
