stages:
  - test
  - build
  - deploy

variables:
  NODE_VERSION: "8"
  ARTIFACT_NAME: "${CI_PROJECT_NAME}.${CI_PIPELINE_ID}.${CI_COMMIT_SHA}"

#
# test stage tasks
#
test_project:
  stage: test
  before_script:
    - . envcfg
    - npm install
  script:
    - npm run lint
    - npm run test


#
# build stage tasks
#
build_project:
  stage: build
  artifacts:
    name: "${ARTIFACT_NAME}"
    when: on_success
    paths:
      - ./
  before_script:
    - . envcfg
    - npm install
  script:
    - NODE_ENV="production" npm run build
  after_script:
    - rm -rf .git

#
# deploy stage tasks
#
#deploy_feature:
#  stage: deploy
#  only:
#    - /^feature\/.*$/
#    - merge-requests
#  when: manual
#  environment:
#    name: ${CI_COMMIT_REF_NAME}
##    on_stop: stop_feature
#  dependencies:
#    - build_project
#  script:
#    - ssh ${REMOTE_FEATURE_USER}@${REMOTE_FEATURE_HOST} "pmci prepare ${CI_COMMIT_REF_SLUG}"
#    - rsync -az . "${REMOTE_FEATURE_USER}@${REMOTE_FEATURE_HOST}:~/tmp/deployments/${CI_COMMIT_REF_SLUG}"
#    - ssh ${REMOTE_FEATURE_USER}@${REMOTE_FEATURE_HOST} "webctl deploy ${CI_COMMIT_REF_SLUG}"
#    - ssh ${REMOTE_FEATURE_USER}@${REMOTE_FEATURE_HOST} "webctl start ${CI_COMMIT_REF_SLUG}"

#stop_deploy_feature:
#  stage: deploy
#  only:
#    - /^feature\/.*$/
#    - merge-requests
#  when: manual
#  environment:
#    name: ${CI_COMMIT_REF_NAME}
#    action: stop
#  script:
#    -
