stages:
  - test
  - build
  - deploy

variables:
  NODE_VERSION: "8"

#
# test stage tasks
#
test_project:
  stage: test
  before_script:
    - . envcfg
    - npm install
  script:
    - npm run lint
    - npm run test


#
# build stage tasks
#
build_project:
  stage: build
  artifacts:
    name: "$CI_PROJECT_NAME.$CI_PIPELINE_ID.$CI_COMMIT_SHA"
    when: on_success
    paths:
      - ./
  before_script:
    - . envcfg
    - npm install
  script:
    - NODE_ENV="production" npm run build
  after_script:
    - rm -rf .git

#
# deploy stage tasks
#
deploy_feature:
  stage: deploy
  only:
    - /^feature\/.*$/
    - merge-requests
  when: manual
  environment:
    name: ${CI_COMMIT_REF_NAME}
#    on_stop: stop_feature
  dependencies:
    - build_project
  script:
    - ls -l
    - scp "$CI_PROJECT_NAME.$CI_PIPELINE_ID.$CI_COMMIT_SHA.zip" hpl@sv04.fream.pl:~/
    - ssh hpl@sv04.fream.pl 'pwd'

#stop_deploy_feature:
#  stage: deploy
#  only:
#    - /^feature\/.*$/
#    - merge-requests
#  when: manual
#  environment:
#    name: ${CI_COMMIT_REF_NAME}
#    action: stop
#  script:
#    -
